name = "project_euler"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
bravo = { path = "vendor/bravo" }
recursive = ">= 2.0.0 and < 3.0.0"
glearray = ">= 2.0.0 and < 3.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
file_streams = ">= 1.2.3 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"

[dev-dependencies]
